class CharacterEntities():
    @classmethod
    def convert(self, str_=None):
        
        
        #// Assume the encoding is UTF-8 -> output is UTF-8
        return str_
        #// return utf8_encode($str);
        #// Convert to CP1252
        from_, to_ = CharacterEntities.generatetables()
        return php_str_replace(from_, to_, str_)
    # end def convert
    def generatetables(self):
        
        
        from_ = []
        to_ = []
        i_ = 0
        while i_ < 256:
            
            from_[i_] = to_[i_] = chr(i_)
            i_ += 1
        # end while
        from_[128] = "â¬"
        from_[130] = "â"
        from_[131] = "Æ"
        from_[132] = "â"
        from_[133] = "â¦"
        from_[134] = "â "
        from_[135] = "â¡"
        from_[136] = "Ë"
        from_[137] = "â°"
        from_[138] = "Å "
        from_[139] = "â¹"
        from_[140] = "Å"
        from_[142] = "Å½"
        from_[145] = "â"
        from_[146] = "â"
        from_[147] = "â"
        from_[148] = "â"
        from_[149] = "â¢"
        from_[150] = "â"
        from_[151] = "â"
        from_[152] = "Ë"
        from_[153] = "â¢"
        from_[154] = "Å¡"
        from_[155] = "âº"
        from_[156] = "Å"
        from_[158] = "Å¾"
        from_[159] = "Å¸"
        from_[161] = "Â¡"
        from_[162] = "Â¢"
        from_[163] = "Â£"
        from_[164] = "Â¤"
        from_[165] = "Â¥"
        from_[166] = "Â¦"
        from_[167] = "Â§"
        from_[168] = "Â¨"
        from_[169] = "Â©"
        from_[170] = "Âª"
        from_[171] = "Â«"
        from_[172] = "Â¬"
        from_[174] = "Â®"
        from_[175] = "Â¯"
        from_[176] = "Â°"
        from_[177] = "Â±"
        from_[178] = "Â²"
        from_[179] = "Â³"
        from_[180] = "Â´"
        from_[181] = "Âµ"
        from_[182] = "Â¶"
        from_[183] = "Â·"
        from_[184] = "Â¸"
        from_[185] = "Â¹"
        from_[186] = "Âº"
        from_[187] = "Â»"
        from_[188] = "Â¼"
        from_[189] = "Â½"
        from_[190] = "Â¾"
        from_[191] = "Â¿"
        from_[192] = "Ã"
        from_[193] = "Ã"
        from_[194] = "Ã"
        from_[195] = "Ã"
        from_[196] = "Ã"
        from_[197] = "Ã"
        from_[198] = "Ã"
        from_[199] = "Ã"
        from_[200] = "Ã"
        from_[201] = "Ã"
        from_[202] = "Ã"
        from_[203] = "Ã"
        from_[204] = "Ã"
        from_[205] = "Ã"
        from_[206] = "Ã"
        from_[207] = "Ã"
        from_[208] = "Ã"
        from_[209] = "Ã"
        from_[210] = "Ã"
        from_[211] = "Ã"
        from_[212] = "Ã"
        from_[213] = "Ã"
        from_[214] = "Ã"
        from_[215] = "Ã"
        from_[216] = "Ã"
        from_[217] = "Ã"
        from_[218] = "Ã"
        from_[219] = "Ã"
        from_[220] = "Ã"
        from_[221] = "Ã"
        from_[222] = "Ã"
        from_[223] = "Ã"
        from_[224] = "Ã "
        from_[225] = "Ã¡"
        from_[226] = "Ã¢"
        from_[227] = "Ã£"
        from_[228] = "Ã¤"
        from_[229] = "Ã¥"
        from_[230] = "Ã¦"
        from_[231] = "Ã§"
        from_[232] = "Ã¨"
        from_[233] = "Ã©"
        from_[234] = "Ãª"
        from_[235] = "Ã«"
        from_[236] = "Ã¬"
        from_[237] = "Ã­"
        from_[238] = "Ã®"
        from_[239] = "Ã¯"
        from_[240] = "Ã°"
        from_[241] = "Ã±"
        from_[242] = "Ã²"
        from_[243] = "Ã³"
        from_[244] = "Ã´"
        from_[245] = "Ãµ"
        from_[246] = "Ã¶"
        from_[247] = "Ã·"
        from_[248] = "Ã¸"
        from_[249] = "Ã¹"
        from_[250] = "Ãº"
        from_[251] = "Ã»"
        from_[252] = "Ã¼"
        from_[253] = "Ã½"
        from_[254] = "Ã¾"
        from_[255] = "Ã¿"
        return [from_, to_]
    # end def generatetables
    pass
# end class CharacterEntities
